version: 0.2
phases:
  pre_build: # Add kubeconfig to access to EKS cluster
    commands:
      - "mkdir ~/.kube/"
      - "cp config-sit ~/.kube/config"
  build: # Build Docker image and tag it with the commit sha
    commands:
      - docker build . -t addressbook:latest . 
      - docker tag addressbook:latest 940500454924.dkr.ecr.us-east-1.amazonaws.com/addressbook:latest
  post_build: # Push the Docker image to the ECR
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 940500454924.dkr.ecr.us-east-1.amazonaws.com
      - docker push 940500454924.dkr.ecr.us-east-1.amazonaws.com/addressbook:latest
      - kubectl create -f deployment.yaml
